# Generated by Django 4.2.1 on 2023-07-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
